version: '3.8'

services:
  db:
    container_name: database
    build: ./Database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  data_insertion_service:
    container_name: data_insertion_service
    build: ./app/data_insertion_service
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5001:5001"

  data_display_service:
    container_name: data_display_service
    build: ./app/data_display_service
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5002:5002"

  nginx:
    container_name: nginx
    build: ./app/frontend
    ports:
      - "8080:80"
    depends_on:
      - data_insertion_service
      - data_display_service

volumes:
  db-data:
