version: '3.8'

services:
  data_insertion_service:
    container_name: data_insertion_service
    build: ./app/data_insertion_service
    env_file:
      .env
    ports:
      - "5001:5001"

  data_display_service:
    container_name: data_display_service
    build: ./app/data_display_service
    env_file:
      .env
    ports:
      - "5002:5002"

  nginx:
    container_name: nginx
    build: ./app/frontend
    ports:
      - "8080:80"
    depends_on:
      - data_insertion_service
      - data_display_service

volumes:
  db-data:
